name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    # Adjusted to run at 0 minutes past the hour, every 12 hours (e.g., 00:00, 12:00 UTC)
    - cron: "0 */12 * * *" 
  workflow_dispatch: # Allows manual triggering from the Actions tab
  push:
    branches:
      - main # Runs whenever you push to main

jobs:
  generate:
    permissions:
      contents: write # Crucial permission for the action to commit the file
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Check out the repository code (required for writing files)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Generate the Pac-Man contribution graph SVG
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          # The image is generated as 'pacman-contribution-graph.svg' and 'pacman-contribution-graph-dark.svg'
          github_user_name: ${{ github.repository_owner }}

      # Step 3: Commit and push the generated SVG file back to the main branch
      - name: Commit and push the generated SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update Pac-Man Contribution Graph"
          # Only commit the generated files
          file_pattern: 'pacman-contribution-graph.svg pacman-contribution-graph-dark.svg'
